version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: book-rent-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookrent
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    container_name: book-rent-api
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/app/src
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bookrent?schema=public
      HOST: 0.0.0.0
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - db

volumes:
  pgdata:
